# Generated by Django 5.1.3 on 2024-12-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='AC_Room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Non_AC_Room',
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_type',
            field=models.CharField(max_length=20),
        ),
    ]
