# Generated by Django 5.1.3 on 2024-12-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Cutomer',
        ),
    ]
