# Generated by Django 5.1.3 on 2024-12-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Num_of_Person',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Inprocess', 'Inprocess'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
