# Generated by Django 5.1.3 on 2024-11-16 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 5, 54, 49, 317756)),
        ),
    ]
