# Generated by Django 5.1.3 on 2025-01-10 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 6, 43, 2, 685108)),
        ),
    ]
