# Generated by Django 5.1.3 on 2025-01-10 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 7, 13, 53, 403435)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
