# Generated by Django 5.1.3 on 2025-02-22 17:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=app.models.get_delivery_date),
        ),
    ]
