# Generated by Django 5.1.3 on 2025-01-10 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_datetime_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 7, 22, 40, 129996)),
        ),
    ]
