# Generated by Django 5.1.3 on 2025-01-12 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_profil_buy_now_like_images_delete_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy_now',
            new_name='Order',
        ),
    ]
