# Generated by Django 5.1.3 on 2025-05-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
