# Generated by Django 5.1.3 on 2024-12-01 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2024, 12, 1, 12, 22, 33, 412606))),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
