# Generated by Django 5.1.3 on 2025-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blogs_count_of_like_blogs_count_of_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
