# Generated by Django 5.1.3 on 2024-11-20 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('Description', models.TextField()),
                ('Posted_date', models.DateField(default=datetime.datetime(2024, 11, 20, 8, 41, 22, 945522))),
            ],
        ),
    ]
