# Generated by Django 5.1.3 on 2024-11-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
