# Generated by Django 5.1.3 on 2025-01-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='products',
            new_name='Pro_id',
        ),
    ]
