# Generated by Django 5.1.3 on 2025-01-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_pro_images_images_image_product_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Pro_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
