# Generated by Django 5.1.3 on 2025-06-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='snapuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='snapuser',
            name='username',
        ),
    ]
