# Generated by Django 5.1.3 on 2025-06-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0002_remove_snapuser_email_remove_snapuser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='snapuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='snapuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
